name: openidconnect
description: OpenIdConnect library for flutter.
version: 1.0.47
homepage: https://github.com/4D-Technologies/openidconnect_flutter

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  openidconnect_darwin: ^0.0.1
  openidconnect_linux: ^0.0.1
  openidconnect_platform_interface: ^1.0.17
  openidconnect_web: ^1.0.26
  openidconnect_windows: ^0.0.8
  jwt_decoder: ^2.0.1

  url_launcher: ^6.3.2
  http: ^1.6.0
  retry: ^3.1.2

  native_authentication: <2.0.0
  flutter_secure_storage: ^10.0.0
  cryptography_plus: ^3.0.0

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  mockito: 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      ios:
        default_package: openidconnect_darwin
      macos:
        default_package: openidconnect_darwin
      linux:
        default_package: openidconnect_linux
      web:
        default_package: openidconnect_web
      windows:
        default_package: openidconnect_windows
