---
version: '3'
services:
  keycloak:
    image: marketplace.gcr.io/google/keycloak21
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-mem