name: openidconnect_platform_interface
description: Platform interface for OpenIdConnect.
version: 1.0.13
homepage: https://github.com/Concerti-IO/openidconnect_flutter/tree/main/openidconnect_platform_interface

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  flutter_test:
    sdk: flutter

flutter:
