name: openidconnect_platform_interface
description: Platform interface for OpenIdConnect.
version: 1.0.11
homepage: https://github.com/Concerti-IO/openidconnect_flutter/tree/main/openidconnect_platform_interface

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  mockito: ^5.0.11
  flutter_test:
    sdk: flutter

flutter:
