name: openidconnect_platform_interface
description: Platform interface for OpenIdConnect.
version: 1.0.15
homepage: https://github.com/4D-Technologies/openidconnect_flutter/tree/main/openidconnect_platform_interface

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: '>=3.1.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

flutter:
