name: openidconnect_platform_interface
description: Platform interface for OpenIdConnect.
version: 1.0.13
homepage: https://github.com/Concerti-IO/openidconnect_flutter/tree/main/openidconnect_platform_interface

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  flutter_test:
    sdk: flutter

flutter:
