name: openidconnect
description: OpenIdConnect library for flutter, it can handle discovery and authentication with various methods.
version: 1.0.25
repository: https://github.com/4D-Technologies/openidconnect_flutter/tree/main/packages/openidconnect

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  openidconnect_platform_interface: ^1.0.13
  openidconnect_web: ^1.0.21
  # openidconnect_windows: ^0.0.6
  flutter_secure_storage: ^6.0.0
  jwt_decoder: ^2.0.1

  cryptography: ^2.0.5

  url_launcher: ^6.1.6
  http: ^1.1.0
  retry: ^3.1.0

  # TODO Remove these once native implementations can be added. Refactor so that the native implementations don't need to do the full cycle through.
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        default_package: openidconnect_web
      # windows:
      #   default_package: openidconnect_windows
