name: openidconnect_darwin
description: Darwin implementation for OpenIdConnect.
version: 2.0.0
homepage: https://github.com/4D-Technologies/openidconnect_flutter/tree/main/openidconnect_darwin

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  openidconnect_platform_interface: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: openidconnect
    platforms:
      ios:
        sharedDarwinSource: true
        pluginClass: OpenIdConnectDarwinPlugin
        dartPluginClass: OpenIdConnectDarwin
        fileName: openidconnect_darwin.dart
      macos:
        sharedDarwinSource: true
        pluginClass: OpenIdConnectDarwinPlugin
        dartPluginClass: OpenIdConnectDarwin
        fileName: openidconnect_darwin.dart
