name: openidconnect_windows
description: Windows implementation for OpenIdConnect.
version: 0.0.7
homepage: https://github.com/Concerti-IO/openidconnect_flutter/tree/main/openidconnect_windows

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  openidconnect_platform_interface: ^1.0.16
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: openidconnect
    platforms:
      windows:
        dartPluginClass: OpenIdConnectWindows
        fileName: openidconnect_windows.dart
